version: '3'
services:
  rundeck:
    build:
      context: .
      args:
        IMAGE: rundeck/rundeck:4.6.0
    container_name: rundeck
    hostname: rundeck
    ports:
    - 4440:4440
    environment:
      RUNDECK_GRAILS_URL: 'http://localhost:4440'
      RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_NAME: org.rundeck.amazon-s3
      RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_ENDPOINT: http://minio:9000/
      RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_BUCKET: rundeck
      RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_REGION: us-east-1
      RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_PATHSTYLE: "true"
      RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_ACCESSKEY: minioadmin
      RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_SECRETKEY: minioadmin
  minio:
    image: minio/minio:latest
    container_name: minio
    hostname: minio
    ports:
      - 9000:9000
      - 9001:9001
    entrypoint: sh
    command: -c 'mkdir -p /rundeck/rundeck && /opt/bin/minio server /rundeck --console-address ":9001"'
    environment:
        MINIO_ROOT_USER: minioadmin
        MINIO_ROOT_PASSWORD: minioadmin
